# Generated by Django 4.2.11 on 2024-04-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_mylist_myrating_alter_movie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='watch',
        ),
    ]
