# Generated by Django 4.2.11 on 2024-04-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_movie_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_logo',
            field=models.ImageField(blank=True, upload_to='movie_logos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.IntegerField(max_length=200),
        ),
    ]
